backend/routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('admin.login');
});

Route::prefix('reader')->name('reader.')->group(function() {
    Route::middleware(['guest:reader'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:reader'])->group(function() {
        //Route::get('/home', [App\Http\Controllers\Reader\HomeController::class, 'index'])->name('home');
        Route::get('/home', function () {
            return redirect('/api/documentation');
        })->name('home');
        Route::post('/logout', [App\Http\Controllers\Reader\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

Route::prefix('admin')->name('admin.')->group(function() {
    Route::middleware(['guest:admin'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:admin', 'is_status_true'])->group(function() {
        Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
        Route::post('/logout', [App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('profile');
        Route::patch('/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('profile.update');

        Route::resource('/roles', App\Http\Controllers\Admin\RoleController::class);
        Route::resource('/admin', App\Http\Controllers\Admin\AdminController::class);
        Route::patch('/admin/{id}/update/status', [App\Http\Controllers\Admin\AdminController::class, 'updateAdminStatus'])->name('admin.update.status');

        Route::resource('/users', App\Http\Controllers\Admin\UserController::class);
        Route::patch('/users/{id}/update/status', [App\Http\Controllers\Admin\UserController::class, 'updateUserStatus'])->name('users.update.status');

        Route::prefix('settings')->name('setting.')->group(function() {
            Route::get('/', [App\Http\Controllers\Admin\SettingController::class, 'index'])->name('index');
            Route::post('/store', [App\Http\Controllers\Admin\SettingController::class, 'store'])->name('store');
            Route::patch('/{id}/update', [App\Http\Controllers\Admin\SettingController::class, 'update'])->name('update');
            Route::delete('/{id}/destroy', [App\Http\Controllers\Admin\SettingController::class, 'destroy'])->name('destroy');
        });

        Route::resource('/language', App\Http\Controllers\Admin\LanguageController::class);

        Route::resource('/menus', App\Http\Controllers\Admin\MenuController::class);
        Route::post('/menus/position/{id}/update', [App\Http\Controllers\Admin\MenuController::class, 'updatePosition'])->name('menus.position.update');

        Route::resource('/pages', App\Http\Controllers\Admin\PageController::class);
        Route::post('/pages/position/{id}/update', [App\Http\Controllers\Admin\PageController::class, 'updatePosition'])->name('pages.position.update');
        Route::resource('pages.banners', App\Http\Controllers\Admin\BannerController::class);

        Route::resource('/marks', App\Http\Controllers\Admin\MarkController::class);
        Route::post('/marks/position/{id}/update', [App\Http\Controllers\Admin\MarkController::class, 'updatePosition'])->name('marks.position.update');

        Route::resource('/certificates', App\Http\Controllers\Admin\CertificateController::class);
        Route::post('/certificates/position/{id}/update', [App\Http\Controllers\Admin\CertificateController::class, 'updatePosition'])->name('certificates.position.update');

        Route::resource('/facts', App\Http\Controllers\Admin\FactController::class);
        Route::post('/facts/position/{id}/update', [App\Http\Controllers\Admin\FactController::class, 'updatePosition'])->name('facts.position.update');

        Route::resource('/why-wes', App\Http\Controllers\Admin\WhyWeController::class);
        Route::post('/why-wes/position/{id}/update', [App\Http\Controllers\Admin\WhyWeController::class, 'updatePosition'])->name('why-wes.position.update');

        Route::resource('/abouts', App\Http\Controllers\Admin\AboutController::class);
        Route::post('/abouts/position/{id}/update', [App\Http\Controllers\Admin\AboutController::class, 'updatePosition'])->name('abouts.position.update');

        Route::resource('/services', App\Http\Controllers\Admin\ServiceController::class);
        Route::post('/services/position/{id}/update', [App\Http\Controllers\Admin\ServiceController::class, 'updatePosition'])->name('services.position.update');

        Route::resource('/tag-description-services', App\Http\Controllers\Admin\TagDescriptionServiceController::class);
        Route::post('/tag-description-services/position/{id}/update', [App\Http\Controllers\Admin\TagDescriptionServiceController::class, 'updatePosition'])->name('tag-description-services.position.update');

        Route::resource('/description-services', App\Http\Controllers\Admin\DescriptionServiceController::class);
        Route::post('/description-services/position/{id}/update', [App\Http\Controllers\Admin\DescriptionServiceController::class, 'updatePosition'])->name('description-services.position.update');

        Route::resource('/tags', App\Http\Controllers\Admin\TagController::class);
        Route::post('/tags/position/{id}/update', [App\Http\Controllers\Admin\TagController::class, 'updatePosition'])->name('tags.position.update');

        Route::resource('/blogs', App\Http\Controllers\Admin\BlogController::class);
        Route::post('/blogs/position/{id}/update', [App\Http\Controllers\Admin\BlogController::class, 'updatePosition'])->name('blogs.position.update');

        Route::resource('blogs.reviews', App\Http\Controllers\Admin\ReviewController::class);
        Route::post('/reviews/position/{id}/update', [App\Http\Controllers\Admin\ReviewController::class, 'updatePosition'])->name('reviews.position.update');

        Route::resource('/tag-masters', App\Http\Controllers\Admin\TagMasterController::class);
        Route::post('/tag-masters/position/{id}/update', [App\Http\Controllers\Admin\TagMasterController::class, 'updatePosition'])->name('tag-masters.position.update');

        Route::resource('/masters', App\Http\Controllers\Admin\MasterController::class);
        Route::post('/masters/position/{id}/update', [App\Http\Controllers\Admin\MasterController::class, 'updatePosition'])->name('masters.position.update');

        Route::resource('/phones', App\Http\Controllers\Admin\PhoneController::class);
        Route::resource('/emails', App\Http\Controllers\Admin\EmailController::class);

        Route::resource('/subscribes', App\Http\Controllers\Admin\SubscribeController::class);
        Route::resource('/feedbacks', App\Http\Controllers\Admin\FeedbackController::class);
    });
});

Route::get('optimize-clear', function () {
    Artisan::call('optimize:clear');
    return back()->with('fail', 'Optimize clear!');
})->name('optimizeClear');

Route::get('storage-link', function () {
    Artisan::call('storage:link');
    return back()->with('fail', 'Storage link!');
})->name('storageLink');

backend/resources/views/admin/admin/_form.blade.php
<x-forms.simple-text :model="$admin ?? null" name="name" label="Имя" />

<x-forms.simple-text :model="$admin ?? null" name="email" label="Email" />

<div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
    <label for="password" class="control-label">@if($formMode == 'create') {{ 'Пароль' }} @else {{ 'Обновить Пароль' }} @endif</label>
    <input class="form-control" name="password" type="text" id="password">
    {!! $errors->first('password', '<p class="text-danger">:message</p>') !!}
</div>
<hr>

@if($formMode == 'create')
    <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : ''}}">
        <label for="password_confirmation" class="control-label">{{ 'Повторить Пароль' }}</label>
        <input class="form-control" name="password_confirmation" type="text" id="password_confirmation">
        {!! $errors->first('password_confirmation', '<p class="text-danger">:message</p>') !!}
    </div>
    <hr>
@endif

@if($formMode == 'edit')
    <input name="admin_id" type="hidden" value="{{$admin->id}}">
@endif

@if ($roles)
    <div class="form-group col-md-6 {{ $errors->has('roles') ? 'has-error' : '' }}">
        <label for="roles" class="control-label">{{ 'Роли' }}</label>
        <select name="roles" id="roles" class="form-control js-example-basic-single" required>
            @foreach ($roles as $item)
                <option value="{{ $item }}" @if (isset($adminRole) && $item == $adminRole) selected @endif>
                    <b>{{ $item }}</b>
                </option>
            @endforeach
        </select>
        {!! $errors->first('roles', '<p class="text-danger">:message</p>') !!}
    </div>
    <hr>
@endif

<x-forms.simple-button :formMode="$formMode" />

backend/resources/views/admin/admin/create.blade.php
@extends('adminlte::page')

@section('title', 'Добавить Администратора')

@section('content_header')
    <h1>Добавить Администратора</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.admin.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.admin.store') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.admin._form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/admin/edit.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать Администратора')

@section('content_header')
    <h1>Редактировать Администратора</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.admin.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.admin.update', $admin) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.admin._form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/admin/index.blade.php
@extends('adminlte::page')

@section('title', 'Администраторы')

@section('content_header')
    <h1>Администраторы</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            @can('создание-администратора')
                                <a href="{{ route('admin.admin.create') }}" title="Добавить" class="btn btn-success btn-sm">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Добавить
                                </a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive" id="tblSort">
                            <table id="tblData" class="table table-bordered table-striped dataTable dtr-inline">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Имя</th>
                                    <th>Email</th>
                                    <th>Роли</th>
                                    <th>Статус</th>
                                    <th>Действие</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($admin as $item)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{$item->name}}</td>
                                        <td>{{$item->email}}</td>
                                        <td>
                                            @if(!empty($item->getRoleNames()))
                                                @foreach($item->getRoleNames() as $v)
                                                    <a href="{{ route('admin.roles.show', $item->roles[0]?->id) }}">
                                                        <span class="badge rounded-pill bg-dark">{{ $v }}</span>
                                                    </a>
                                                @endforeach
                                            @endif
                                        </td>
                                        <td>
                                            @if($item->status == 1)
                                                <span class="badge rounded-pill bg-success">Активирован</span>
                                            @else
                                                <span class="badge rounded-pill bg-danger">Деактивирован</span>
                                            @endif
                                        </td>
                                        <td>
                                            @can('все-администраторы')
                                                <form method="POST" action="{{ route('admin.admin.update.status', $item->id) }}" accept-charset="UTF-8" style="display:inline;">
                                                    {{ method_field('PATCH') }}
                                                    {{ csrf_field() }}
                                                    <input type="hidden" name="status" value="{{ $item->status == 1 ? 0 : 1 }}">
                                                    <button type="submit" class="btn btn-{{ $item->status == 1 ? 'danger' : 'success' }} btn-sm mb-2" title="@if($item->status == 1) Деактивировать @else Активировать @endif">
                                                        @if($item->status == 1)
                                                            <i class="fa fa-lock" aria-hidden="true"></i>
                                                        @else
                                                            <i class="fa fa-lock-open" aria-hidden="true"></i>
                                                        @endif
                                                    </button>
                                                </form>

                                                <a href="{{ route('admin.admin.show', $item) }}" title="Просмотр" class="btn btn-info btn-sm mb-2">
                                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('редактирование-администратора')
                                                <a href="{{ route('admin.admin.edit', $item) }}" title="Редактировать" class="btn btn-primary btn-sm mb-2">
                                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('удаление-администратора')
                                                <form method="POST" action="{{ route('admin.admin.destroy', $item) }}" accept-charset="UTF-8" style="display:inline;">
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-danger btn-sm mb-2" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $item->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $item->name }}?&quot;)">
                                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                                    </button>
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="6" class="text-center">
                                            Администратор еще не добавлен!
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                            <div class="pagination-wrapper">
                                {!! $admin->appends(['search' => Request::get('search')])->render() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/admin/show.blade.php
@extends('adminlte::page')

@section('title', 'Просмотр Администратора')

@section('content_header')
    <h1>Просмотр Администратора</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.admin.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                            @can('редактирование-администратора')
                                <a href="{{ route('admin.admin.edit', $admin) }}" title="Редактировать" class="btn btn-primary">
                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i> Редактировать
                                </a>
                            @endcan
                            @can('удаление-администратора')
                                <form method="POST" action="{{ route('admin.admin.destroy', $admin) }}" accept-charset="UTF-8" style="display:inline;">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $admin->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $admin->name }}?&quot;)">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Удалить
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>ID</th>
                                    <td>{{ $admin->id }}</td>
                                </tr>
                                <tr>
                                    <th>Имя</th>
                                    <td>{{ $admin->name }}</td>
                                </tr>
                                <tr>
                                    <th>Email</th>
                                    <td>{{ $admin->email }}</td>
                                </tr>
                                <tr>
                                    <th>Роли</th>
                                    <td>
                                        @if(!empty($admin->getRoleNames()))
                                            @foreach($admin->getRoleNames() as $v)
                                                <a href="{{ route('admin.roles.show', $admin->roles[0]?->id) }}">
                                                    <span class="badge rounded-pill bg-dark">{{ $v }}</span>
                                                </a>
                                            @endforeach
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <th>Статус</th>
                                    <td>
                                        @if($admin->status == 1)
                                            <span class="badge rounded-pill bg-success">Активирован</span>
                                        @else
                                            <span class="badge rounded-pill bg-danger">Деактивирован</span>
                                        @endif
                                    </td>
                                </tr>
                                <tr>
                                    <th>Дата создания</th>
                                    <td>{{ $admin->created_at->format('d.m.Y') }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')
@stop