backend/routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('admin.login');
});

Route::prefix('reader')->name('reader.')->group(function() {
    Route::middleware(['guest:reader'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:reader'])->group(function() {
        //Route::get('/home', [App\Http\Controllers\Reader\HomeController::class, 'index'])->name('home');
        Route::get('/home', function () {
            return redirect('/api/documentation');
        })->name('home');
        Route::post('/logout', [App\Http\Controllers\Reader\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

Route::prefix('admin')->name('admin.')->group(function() {
    Route::middleware(['guest:admin'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:admin', 'is_status_true'])->group(function() {
        Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
        Route::post('/logout', [App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('profile');
        Route::patch('/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('profile.update');

        Route::resource('/roles', App\Http\Controllers\Admin\RoleController::class);
        Route::resource('/admin', App\Http\Controllers\Admin\AdminController::class);
        Route::patch('/admin/{id}/update/status', [App\Http\Controllers\Admin\AdminController::class, 'updateAdminStatus'])->name('admin.update.status');

        Route::resource('/users', App\Http\Controllers\Admin\UserController::class);
        Route::patch('/users/{id}/update/status', [App\Http\Controllers\Admin\UserController::class, 'updateUserStatus'])->name('users.update.status');

        Route::prefix('settings')->name('setting.')->group(function() {
            Route::get('/', [App\Http\Controllers\Admin\SettingController::class, 'index'])->name('index');
            Route::post('/store', [App\Http\Controllers\Admin\SettingController::class, 'store'])->name('store');
            Route::patch('/{id}/update', [App\Http\Controllers\Admin\SettingController::class, 'update'])->name('update');
            Route::delete('/{id}/destroy', [App\Http\Controllers\Admin\SettingController::class, 'destroy'])->name('destroy');
        });

        Route::resource('/language', App\Http\Controllers\Admin\LanguageController::class);

        Route::resource('/menus', App\Http\Controllers\Admin\MenuController::class);
        Route::post('/menus/position/{id}/update', [App\Http\Controllers\Admin\MenuController::class, 'updatePosition'])->name('menus.position.update');

        Route::resource('/pages', App\Http\Controllers\Admin\PageController::class);
        Route::post('/pages/position/{id}/update', [App\Http\Controllers\Admin\PageController::class, 'updatePosition'])->name('pages.position.update');
        Route::resource('pages.banners', App\Http\Controllers\Admin\BannerController::class);

        Route::resource('/marks', App\Http\Controllers\Admin\MarkController::class);
        Route::post('/marks/position/{id}/update', [App\Http\Controllers\Admin\MarkController::class, 'updatePosition'])->name('marks.position.update');

        Route::resource('/certificates', App\Http\Controllers\Admin\CertificateController::class);
        Route::post('/certificates/position/{id}/update', [App\Http\Controllers\Admin\CertificateController::class, 'updatePosition'])->name('certificates.position.update');

        Route::resource('/facts', App\Http\Controllers\Admin\FactController::class);
        Route::post('/facts/position/{id}/update', [App\Http\Controllers\Admin\FactController::class, 'updatePosition'])->name('facts.position.update');

        Route::resource('/why-wes', App\Http\Controllers\Admin\WhyWeController::class);
        Route::post('/why-wes/position/{id}/update', [App\Http\Controllers\Admin\WhyWeController::class, 'updatePosition'])->name('why-wes.position.update');

        Route::resource('/abouts', App\Http\Controllers\Admin\AboutController::class);
        Route::post('/abouts/position/{id}/update', [App\Http\Controllers\Admin\AboutController::class, 'updatePosition'])->name('abouts.position.update');

        Route::resource('/services', App\Http\Controllers\Admin\ServiceController::class);
        Route::post('/services/position/{id}/update', [App\Http\Controllers\Admin\ServiceController::class, 'updatePosition'])->name('services.position.update');

        Route::resource('/tag-description-services', App\Http\Controllers\Admin\TagDescriptionServiceController::class);
        Route::post('/tag-description-services/position/{id}/update', [App\Http\Controllers\Admin\TagDescriptionServiceController::class, 'updatePosition'])->name('tag-description-services.position.update');

        Route::resource('/description-services', App\Http\Controllers\Admin\DescriptionServiceController::class);
        Route::post('/description-services/position/{id}/update', [App\Http\Controllers\Admin\DescriptionServiceController::class, 'updatePosition'])->name('description-services.position.update');

        Route::resource('/tags', App\Http\Controllers\Admin\TagController::class);
        Route::post('/tags/position/{id}/update', [App\Http\Controllers\Admin\TagController::class, 'updatePosition'])->name('tags.position.update');

        Route::resource('/blogs', App\Http\Controllers\Admin\BlogController::class);
        Route::post('/blogs/position/{id}/update', [App\Http\Controllers\Admin\BlogController::class, 'updatePosition'])->name('blogs.position.update');

        Route::resource('blogs.reviews', App\Http\Controllers\Admin\ReviewController::class);
        Route::post('/reviews/position/{id}/update', [App\Http\Controllers\Admin\ReviewController::class, 'updatePosition'])->name('reviews.position.update');

        Route::resource('/tag-masters', App\Http\Controllers\Admin\TagMasterController::class);
        Route::post('/tag-masters/position/{id}/update', [App\Http\Controllers\Admin\TagMasterController::class, 'updatePosition'])->name('tag-masters.position.update');

        Route::resource('/masters', App\Http\Controllers\Admin\MasterController::class);
        Route::post('/masters/position/{id}/update', [App\Http\Controllers\Admin\MasterController::class, 'updatePosition'])->name('masters.position.update');

        Route::resource('/phones', App\Http\Controllers\Admin\PhoneController::class);
        Route::resource('/emails', App\Http\Controllers\Admin\EmailController::class);

        Route::resource('/subscribes', App\Http\Controllers\Admin\SubscribeController::class);
        Route::resource('/feedbacks', App\Http\Controllers\Admin\FeedbackController::class);
    });
});

Route::get('optimize-clear', function () {
    Artisan::call('optimize:clear');
    return back()->with('fail', 'Optimize clear!');
})->name('optimizeClear');

Route::get('storage-link', function () {
    Artisan::call('storage:link');
    return back()->with('fail', 'Storage link!');
})->name('storageLink');

backend/app/Models/Master.php
<?php

namespace App\Models;

use App\Contracts\HasTitleContract;
use App\Contracts\HasDescriptionContract;
use App\Traits\HasTitleTrait;
use App\Traits\HasDescriptionTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Facades\Storage;

/**
 * App\Models\Master
 *
 * @property int $id
 * @property string $image
 * @property string $name
 * @property string $reviews
 * @property int $title_tr
 * @property int $description_tr
 * @property boolean $is_published
 * @property int $position
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \App\Models\Translate $title
 * @property-read \App\Models\Translate $description
 */

class Master extends Model implements HasTitleContract, HasDescriptionContract
{
    use HasFactory, HasTitleTrait, HasDescriptionTrait;

    const IMAGE_PATH = 'images/masters';

    protected $table = 'masters';

    protected $primaryKey = 'id';

    protected $guarded = [];

    public function tagMasters(): BelongsToMany
    {
        return $this->belongsToMany(TagMaster::class, 'tag_master_masters');
    }

    public function getImageUrlAttribute(): string|null
    {
        return $this->image ? Storage::disk('custom')->url(self::IMAGE_PATH . '/' . $this->image) : '';
    }
}

backend/app/Http/Controllers/Admin/MasterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Http\Requests\Admin\Master\StoreMasterRequest;
use App\Http\Requests\Admin\Master\UpdateMasterPositionRequest;
use App\Http\Requests\Admin\Master\UpdateMasterRequest;

use App\Models\Master;
use App\Services\Admin\TagMaster\TagMasterService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use App\Services\Admin\Master\MasterService;

class MasterController extends Controller
{
    public function __construct(protected MasterService $masterService)
    {
        $this->middleware('auth:admin');
        $this->middleware('permission:все-мастера', ['only' => ['index','show']]);
        $this->middleware('permission:создание-мастера', ['only' => ['create','store']]);
        $this->middleware('permission:редактирование-мастера', ['only' => ['edit','update', 'updatePosition']]);
        $this->middleware('permission:удаление-мастера', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $masters = $this->masterService->getMasters();

        return view('admin.masters.index', compact('masters'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $langs = $this->masterService->getLangs();
        $tags = (new TagMasterService())->getTagMasterCollection();

        return view('admin.masters.create', compact('langs', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreMasterRequest $request): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $this->masterService->createMaster($data);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.masters.index')->with('success', config('sessionmessages.successfully_added'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Master $master): View
    {
        return view('admin.masters.show', compact('master'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Master $master): View
    {
        $langs = $this->masterService->getLangs();
        $tags = (new TagMasterService())->getTagMasterCollection();

        return view('admin.masters.edit', compact('master', 'langs', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateMasterRequest $request, Master $master): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $this->masterService->updateMaster($master, $data);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.masters.index')->with('success', config('sessionmessages.successfully_updated'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Master $master): RedirectResponse
    {
        DB::beginTransaction();
        try {
            $this->masterService->deleteMaster($master);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.masters.index')->with('success', config('sessionmessages.successfully_deleted'));
    }

    public function updatePosition(UpdateMasterPositionRequest $request, string $id): int|bool
    {
        $data = $request->validated();

        if (isset($data['position']) && !empty($data['position'])) {
            $this->masterService->updateMasterPosition($data, $id);
        }

        return false;
    }
}

backend/resources/views/admin/masters/create.blade.php
@extends('adminlte::page')

@section('title', 'Добавить Мастера')

@section('content_header')
    <h1>Добавить Мастера</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.masters.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.masters.store') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.masters._form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .select2-container .select2-selection--single {
            height: 40px !important;
        }
    </style>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            $('.select2').select2();
        });
        $(document).on('change', '.photo', function(){
            const file = this.files[0];
            var previewElement = $('#image-preview-image');
            previewElement.css('display', 'block');
            if (file){
                let reader = new FileReader();
                reader.onload = function(event){
                    previewElement.attr('src', event.target.result);
                }
                reader.readAsDataURL(file);
            }
        });
    </script>
@stop

@section('plugins.Select2', true)

backend/resources/views/admin/masters/edit.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать Мастера')

@section('content_header')
    <h1>Редактировать Мастера</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.masters.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.masters.update', ['master' => $master]) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.masters._form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <style>
        .select2-container .select2-selection--single {
            height: 40px !important;
        }
    </style>
@stop

@section('js')
    <script>
        $(document).ready(function () {
            Fancybox.bind('[data-fancybox="image"]', {
                keyboard: true,
            });
            $('.select2').select2();
        });
    </script>
@stop

@section('plugins.fancybox', true)
@section('plugins.Select2', true)

backend/resources/views/admin/masters/index.blade.php
@extends('adminlte::page')

@section('title', 'Мастера')

@section('content_header')
    <h1>Мастера</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            @can('создание-мастера')
                                <a href="{{ route('admin.masters.create') }}" class="btn btn-success btn-sm" title="Добавить">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Добавить
                                </a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive" id="tblSort">
                            <table id="tblData" class="table table-bordered table-striped dataTable dtr-inline">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>Имя</th>
                                        <th>Статус</th>
                                        <th>Действие</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $count = 1;
                                    @endphp
                                    @forelse($masters as $item)
                                        <tr>
                                            <td data-id="{{$item->id}}">
                                                {{$masters->perPage()*($masters->currentPage()-1)+$count}}
                                            </td>
                                            <td>
                                                {{ $item->id }}
                                            </td>
                                            <td>{{ $item->name }}</td>
                                            <td>
                                                @if($item->is_published == 1)
                                                    <span class="badge rounded-pill bg-success">
                                                        Опубликована
                                                    </span>
                                                @else
                                                    <span class="badge rounded-pill bg-danger">
                                                        Не опубликована
                                                    </span>
                                                @endif
                                            </td>
                                            <td>
                                                @can('все-мастера')
                                                    <a href="{{ route('admin.masters.show', ['master' => $item]) }}" class="btn btn-info btn-sm mb-2" title="Просмотр">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                @endcan
                                                @can('редактирование-мастера')
                                                    <a href="{{ route('admin.masters.edit', ['master' => $item]) }}" class="btn btn-primary btn-sm mb-2" title="Редактировать">
                                                        <i class="fa fa-fw fa-edit" aria-hidden="true"></i>
                                                    </a>
                                                @endcan
                                                @can('удаление-мастера')
                                                    <form method="POST" action="{{ route('admin.masters.destroy', ['master' => $item]) }}" accept-charset="UTF-8" style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-danger btn-sm mb-2" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $item->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $item->name }}?&quot;)">
                                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                                        </button>
                                                    </form>
                                                @endcan
                                            </td>
                                        </tr>
                                        @php
                                            $count++;
                                        @endphp
                                    @empty
                                        <tr>
                                            <td align="center" class="text-danger" colspan="5">
                                                Мастера не найдены
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>Имя</th>
                                        <th>Статус</th>
                                        <th>Действие</th>
                                    </tr>
                                </tfoot>
                            </table>
                            <div class="pagination-wrapper">
                                @if(is_object($masters))
                                    {!! $masters->links() !!}
                                @endif
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

@stop

@section('js')
    <script>
        $(document).ready(function () {
            //console.log($(1).find('td:eq(0)').data('id'));
            $("#tblSort tbody").sortable({
                cursor: "move",
                placeholder: "sortable-placeholder",
                update: function (event, ui) {
                    $(".table tbody tr").each((item, i) => {
                        $(i).find('td:eq(0)').html(item + 1)
                        let position = $(i).find('td:eq(0)').data('id')
                        $.ajax({
                            headers: {
                                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                            },
                            method: 'POST',
                            url: `/admin/masters/position/${position}/update`,
                            data: {position: item + 1}
                        })
                        .done(function (msg) {

                        });
                    });
                },
                helper: function (e, tr) {
                    var $originals = tr.children();
                    var $helper = tr.clone();
                    $helper.children().each(function (index) {
                        $(this).width($originals.eq(index).width());
                    });
                    return $helper;
                }
            }).disableSelection();
        });
    </script>
@stop

@section('plugins.jqueryUi', true)

backend/resources/views/admin/masters/show.blade.php
@extends('adminlte::page')

@section('title', 'Просмотр Мастера')

@section('content_header')
    <h1>Просмотр Мастера</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.masters.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                            @can('редактирование-мастера')
                                <a href="{{ route('admin.masters.edit', ['master' => $master]) }}" class="btn btn-primary" title="Редактировать">
                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i> Редактировать
                                </a>
                            @endcan
                            @can('удаление-мастера')
                                <form method="POST" action="{{ route('admin.masters.destroy', ['master' => $master]) }}" accept-charset="UTF-8" style="display:inline">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $master->title?->ru }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $master->title?->ru }}?&quot;)">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Удалить
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th>
                                        <td>{{ $master->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Изображение </th>
                                        <td>
                                            <a href="{{ $master->image_url }}" data-fancybox="image">
                                                <img id="image-preview" class="rounded" src="{{ $master->image_url }}" style="max-width: 300px;" alt="{{ $master->name }}">
                                            </a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th> Имя </th>
                                        <td> {{ $master->name }} </td>
                                    </tr>
                                    <tr>
                                        <th> Кол-во отзывов </th>
                                        <td> {{ $master->reviews }} </td>
                                    </tr>
                                    <tr>
                                        <th> Расстояние(км) </th>
                                        <td> {{ $master->title?->ru }} </td>
                                    </tr>
                                    <tr>
                                        <th> Опыт работы </th>
                                        <td> {!! $master->description?->ru !!} </td>
                                    </tr>
                                    <tr>
                                        <th> Теги </th>
                                        <td>
                                            @forelse($master->tagMasters as $tag)
                                                <a href="{{ route('admin.tag-masters.show', ['tag_master' => $tag]) }}">{{ $tag->title?->ru }}</a><br>
                                            @empty
                                                Теги не найдены
                                            @endforelse
                                        </td>
                                    </tr>
                                    <tr>
                                        <th> Статус </th>
                                        <td>
                                            @if($master->is_published == 1)
                                                <span class="badge rounded-pill bg-success">
                                                    Опубликована
                                                </span>
                                            @else
                                                <span class="badge rounded-pill bg-danger">
                                                    Не опубликована
                                                </span>
                                            @endif
                                        </td>
                                    </tr>
                                    <tr>
                                        <th> Позиция </th>
                                        <td> {{ $master->position }} </td>
                                    </tr>
                                    <tr>
                                        <th> Дата </th>
                                        <td> {{ $master->created_at?->format('d.m.Y') }} </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        $(document).ready(function () {
            Fancybox.bind('[data-fancybox="image"]', {
                keyboard: true,
            });
        });
    </script>
@stop

@section('plugins.fancybox', true)