backend/routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('admin.login');
});

Route::prefix('reader')->name('reader.')->group(function() {
    Route::middleware(['guest:reader'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:reader'])->group(function() {
        //Route::get('/home', [App\Http\Controllers\Reader\HomeController::class, 'index'])->name('home');
        Route::get('/home', function () {
            return redirect('/api/documentation');
        })->name('home');
        Route::post('/logout', [App\Http\Controllers\Reader\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

Route::prefix('admin')->name('admin.')->group(function() {
    Route::middleware(['guest:admin'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:admin', 'is_status_true'])->group(function() {
        Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
        Route::post('/logout', [App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('profile');
        Route::patch('/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('profile.update');

        Route::resource('/roles', App\Http\Controllers\Admin\RoleController::class);
        Route::resource('/admin', App\Http\Controllers\Admin\AdminController::class);
        Route::patch('/admin/{id}/update/status', [App\Http\Controllers\Admin\AdminController::class, 'updateAdminStatus'])->name('admin.update.status');

        Route::resource('/users', App\Http\Controllers\Admin\UserController::class);
        Route::patch('/users/{id}/update/status', [App\Http\Controllers\Admin\UserController::class, 'updateUserStatus'])->name('users.update.status');

        Route::prefix('settings')->name('setting.')->group(function() {
            Route::get('/', [App\Http\Controllers\Admin\SettingController::class, 'index'])->name('index');
            Route::post('/store', [App\Http\Controllers\Admin\SettingController::class, 'store'])->name('store');
            Route::patch('/{id}/update', [App\Http\Controllers\Admin\SettingController::class, 'update'])->name('update');
            Route::delete('/{id}/destroy', [App\Http\Controllers\Admin\SettingController::class, 'destroy'])->name('destroy');
        });

        Route::resource('/language', App\Http\Controllers\Admin\LanguageController::class);

        Route::resource('/menus', App\Http\Controllers\Admin\MenuController::class);
        Route::post('/menus/position/{id}/update', [App\Http\Controllers\Admin\MenuController::class, 'updatePosition'])->name('menus.position.update');

        Route::resource('/pages', App\Http\Controllers\Admin\PageController::class);
        Route::post('/pages/position/{id}/update', [App\Http\Controllers\Admin\PageController::class, 'updatePosition'])->name('pages.position.update');
        Route::resource('pages.banners', App\Http\Controllers\Admin\BannerController::class);

        Route::resource('/marks', App\Http\Controllers\Admin\MarkController::class);
        Route::post('/marks/position/{id}/update', [App\Http\Controllers\Admin\MarkController::class, 'updatePosition'])->name('marks.position.update');

        Route::resource('/certificates', App\Http\Controllers\Admin\CertificateController::class);
        Route::post('/certificates/position/{id}/update', [App\Http\Controllers\Admin\CertificateController::class, 'updatePosition'])->name('certificates.position.update');

        Route::resource('/facts', App\Http\Controllers\Admin\FactController::class);
        Route::post('/facts/position/{id}/update', [App\Http\Controllers\Admin\FactController::class, 'updatePosition'])->name('facts.position.update');

        Route::resource('/why-wes', App\Http\Controllers\Admin\WhyWeController::class);
        Route::post('/why-wes/position/{id}/update', [App\Http\Controllers\Admin\WhyWeController::class, 'updatePosition'])->name('why-wes.position.update');

        Route::resource('/abouts', App\Http\Controllers\Admin\AboutController::class);
        Route::post('/abouts/position/{id}/update', [App\Http\Controllers\Admin\AboutController::class, 'updatePosition'])->name('abouts.position.update');

        Route::resource('/services', App\Http\Controllers\Admin\ServiceController::class);
        Route::post('/services/position/{id}/update', [App\Http\Controllers\Admin\ServiceController::class, 'updatePosition'])->name('services.position.update');

        Route::resource('/tag-description-services', App\Http\Controllers\Admin\TagDescriptionServiceController::class);
        Route::post('/tag-description-services/position/{id}/update', [App\Http\Controllers\Admin\TagDescriptionServiceController::class, 'updatePosition'])->name('tag-description-services.position.update');

        Route::resource('/description-services', App\Http\Controllers\Admin\DescriptionServiceController::class);
        Route::post('/description-services/position/{id}/update', [App\Http\Controllers\Admin\DescriptionServiceController::class, 'updatePosition'])->name('description-services.position.update');

        Route::resource('/tags', App\Http\Controllers\Admin\TagController::class);
        Route::post('/tags/position/{id}/update', [App\Http\Controllers\Admin\TagController::class, 'updatePosition'])->name('tags.position.update');

        Route::resource('/blogs', App\Http\Controllers\Admin\BlogController::class);
        Route::post('/blogs/position/{id}/update', [App\Http\Controllers\Admin\BlogController::class, 'updatePosition'])->name('blogs.position.update');

        Route::resource('blogs.reviews', App\Http\Controllers\Admin\ReviewController::class);
        Route::post('/reviews/position/{id}/update', [App\Http\Controllers\Admin\ReviewController::class, 'updatePosition'])->name('reviews.position.update');

        Route::resource('/tag-masters', App\Http\Controllers\Admin\TagMasterController::class);
        Route::post('/tag-masters/position/{id}/update', [App\Http\Controllers\Admin\TagMasterController::class, 'updatePosition'])->name('tag-masters.position.update');

        Route::resource('/masters', App\Http\Controllers\Admin\MasterController::class);
        Route::post('/masters/position/{id}/update', [App\Http\Controllers\Admin\MasterController::class, 'updatePosition'])->name('masters.position.update');

        Route::resource('/phones', App\Http\Controllers\Admin\PhoneController::class);
        Route::resource('/emails', App\Http\Controllers\Admin\EmailController::class);

        Route::resource('/subscribes', App\Http\Controllers\Admin\SubscribeController::class);
        Route::resource('/feedbacks', App\Http\Controllers\Admin\FeedbackController::class);
    });
});

Route::get('optimize-clear', function () {
    Artisan::call('optimize:clear');
    return back()->with('fail', 'Optimize clear!');
})->name('optimizeClear');

Route::get('storage-link', function () {
    Artisan::call('storage:link');
    return back()->with('fail', 'Storage link!');
})->name('storageLink');

backend/app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Role\StoreRoleRequest;
use App\Http\Requests\Admin\Role\UpdateRoleRequest;
use App\Services\Admin\Role\RoleService;
use Spatie\Permission\Models\Role;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    public function __construct(protected RoleService $roleService)
    {
        $this->middleware('auth:admin');
        $this->middleware('permission:все-роли', ['only' => ['index','show']]);
        $this->middleware('permission:создание-роли', ['only' => ['create','store']]);
        $this->middleware('permission:редактирование-роли', ['only' => ['edit','update']]);
        $this->middleware('permission:удаление-роли', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $roles = $this->roleService->getRoles();

        return view('admin.role.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $permission = $this->roleService->getPermissions();

        return view('admin.role.create',compact('permission'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRoleRequest $request): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $this->roleService->createRole($data);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.roles.index')->with('success', config('sessionmessages.successfully_added'));
    }

    /**
     * Display the specified resource.
     */
    public function show(Role $role): View
    {
        $rolePermissions = $this->roleService->getRolePermissionsByRoleId($role);

        return view('admin.role.show', compact('role', 'rolePermissions'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Role $role): View
    {
        $permission = $this->roleService->getPermissions();
        $rolePermissions = $this->roleService->getRolePermissionsByRoleIdAll($role);

        return view('admin.role.edit', compact('role', 'permission', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRoleRequest $request, Role $role): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $this->roleService->updateRole($role, $data);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.roles.index')->with('success', config('sessionmessages.successfully_updated'));
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Role $role): RedirectResponse
    {
        DB::beginTransaction();
        try {
            $this->roleService->deleteRole($role);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.roles.index')->with('success', config('sessionmessages.successfully_deleted'));
    }
}

backend/resources/views/admin/role/_form.blade.php
<x-forms.simple-text :model="$role ?? null" name="name" label="Названия" />

<br/>
<hr>
@if($permission)
    @foreach($permission as $value)
        <label>
            <input class="name" name="permission[]" type="checkbox" value="{{$value->name}}" @if(isset($rolePermissions)){{ in_array($value->id, $rolePermissions) ? 'checked="checked"' : ''}}@endif>
            {{ $value->name }}
        </label>
        <br/>
        @if(strpos($value->name, 'удаление') !== false)
            <hr>
        @endif
    @endforeach
@endif

<x-forms.simple-button :formMode="$formMode" />

backend/resources/views/admin/role/create.blade.php
@extends('adminlte::page')

@section('title', 'Добавить Роли')

@section('content_header')
    <h1>Добавить Роли</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.roles.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.roles.store') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.role._form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/role/edit.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать Роли')

@section('content_header')
    <h1>Редактировать Роли</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.roles.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.roles.update', $role) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.role._form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/role/index.blade.php
@extends('adminlte::page')

@section('title', 'Роли')

@section('content_header')
    <h1>Роли</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            @can('создание-роли')
                                <a href="{{ route('admin.roles.create') }}" title="Добавить" class="btn btn-success btn-sm">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Добавить
                                </a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive" id="tblSort">
                            <table id="tblData" class="table table-bordered table-striped dataTable dtr-inline">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Название</th>
                                    <th>Действие</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($roles as $item)
                                    <tr>
                                        <td>{{$loop->iteration}}</td>
                                        <td>{{$item->name}}</td>
                                        <td>
                                            @can('все-роли')
                                                <a href="{{ route('admin.roles.show', $item) }}" title="Просмотр" class="btn btn-info btn-sm mb-2">
                                                    <i class="fa fa-eye" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('редактирование-роли')
                                                <a href="{{ route('admin.roles.edit', $item) }}" title="Редактировать" class="btn btn-primary btn-sm mb-2">
                                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i>
                                                </a>
                                            @endcan
                                            @can('удаление-роли')
                                                <form method="POST" action="{{ route('admin.roles.destroy', $item) }}" accept-charset="UTF-8" style="display:inline">
                                                    {{ method_field('DELETE') }}
                                                    {{ csrf_field() }}
                                                    <button type="submit" class="btn btn-danger btn-sm mb-2" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $item->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $item->name }}?&quot;)">
                                                        <i class="fa fa-trash" aria-hidden="true"></i>
                                                    </button>
                                                </form>
                                            @endcan
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="4" class="text-center">
                                            Роль еще не добавлен!
                                        </td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                            <div class="pagination-wrapper">
                                {!! $roles->appends(['search' => Request::get('search')])->render() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/role/show.blade.php
@extends('adminlte::page')

@section('title', 'Просмотр Роли')

@section('content_header')
    <h1>Просмотр Роли</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.roles.index') }}" class="btn btn-warning">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                            @can('редактирование-роли')
                                <a href="{{ route('admin.roles.edit', $role) }}" title="Редактировать" class="btn btn-primary">
                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i> Редактировать
                                </a>
                            @endcan
                            @can('удаление-роли')
                                <form method="POST" action="{{ route('admin.roles.destroy', $role) }}" accept-charset="UTF-8" style="display:inline">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $role->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $role->name }}?&quot;)">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Удалить
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                <tr>
                                    <th>ID</th>
                                    <td>{{ $role->id }}</td>
                                </tr>
                                <tr>
                                    <th>Название</th>
                                    <td>{{ $role->name }}</td>
                                </tr>
                                <tr>
                                    @if(!empty($rolePermissions))
                                        <th>Доступы</th>
                                        <td>
                                            @foreach($rolePermissions as $v)
                                                {{ $v->name }}
                                                <br>
                                            @endforeach
                                        </td>
                                    @endif
                                </tr>
                                <tr>
                                    <th>Дата создания</th>
                                    <td>{{ $role->created_at?->format('d.m.Y') }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop