backend/routes/web.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('admin.login');
});

Route::prefix('reader')->name('reader.')->group(function() {
    Route::middleware(['guest:reader'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Reader\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:reader'])->group(function() {
        //Route::get('/home', [App\Http\Controllers\Reader\HomeController::class, 'index'])->name('home');
        Route::get('/home', function () {
            return redirect('/api/documentation');
        })->name('home');
        Route::post('/logout', [App\Http\Controllers\Reader\Auth\LoginController::class, 'logout'])->name('logout');
    });
});

Route::prefix('admin')->name('admin.')->group(function() {
    Route::middleware(['guest:admin'])->group(function() {
        Route::get('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('login');
        Route::post('/login', [App\Http\Controllers\Admin\Auth\LoginController::class, 'login'])->name('check');
    });

    Route::middleware(['auth:admin', 'is_status_true'])->group(function() {
        Route::get('/home', [App\Http\Controllers\Admin\HomeController::class, 'index'])->name('home');
        Route::post('/logout', [App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('logout');

        Route::get('/profile', [App\Http\Controllers\Admin\ProfileController::class, 'index'])->name('profile');
        Route::patch('/profile/update', [App\Http\Controllers\Admin\ProfileController::class, 'update'])->name('profile.update');

        Route::resource('/roles', App\Http\Controllers\Admin\RoleController::class);
        Route::resource('/admin', App\Http\Controllers\Admin\AdminController::class);
        Route::patch('/admin/{id}/update/status', [App\Http\Controllers\Admin\AdminController::class, 'updateAdminStatus'])->name('admin.update.status');

        Route::resource('/users', App\Http\Controllers\Admin\UserController::class);
        Route::patch('/users/{id}/update/status', [App\Http\Controllers\Admin\UserController::class, 'updateUserStatus'])->name('users.update.status');

        Route::prefix('settings')->name('setting.')->group(function() {
            Route::get('/', [App\Http\Controllers\Admin\SettingController::class, 'index'])->name('index');
            Route::post('/store', [App\Http\Controllers\Admin\SettingController::class, 'store'])->name('store');
            Route::patch('/{id}/update', [App\Http\Controllers\Admin\SettingController::class, 'update'])->name('update');
            Route::delete('/{id}/destroy', [App\Http\Controllers\Admin\SettingController::class, 'destroy'])->name('destroy');
        });

        Route::resource('/language', App\Http\Controllers\Admin\LanguageController::class);

        Route::resource('/menus', App\Http\Controllers\Admin\MenuController::class);
        Route::post('/menus/position/{id}/update', [App\Http\Controllers\Admin\MenuController::class, 'updatePosition'])->name('menus.position.update');

        Route::resource('/pages', App\Http\Controllers\Admin\PageController::class);
        Route::post('/pages/position/{id}/update', [App\Http\Controllers\Admin\PageController::class, 'updatePosition'])->name('pages.position.update');
        Route::resource('pages.banners', App\Http\Controllers\Admin\BannerController::class);

        Route::resource('/marks', App\Http\Controllers\Admin\MarkController::class);
        Route::post('/marks/position/{id}/update', [App\Http\Controllers\Admin\MarkController::class, 'updatePosition'])->name('marks.position.update');

        Route::resource('/certificates', App\Http\Controllers\Admin\CertificateController::class);
        Route::post('/certificates/position/{id}/update', [App\Http\Controllers\Admin\CertificateController::class, 'updatePosition'])->name('certificates.position.update');

        Route::resource('/facts', App\Http\Controllers\Admin\FactController::class);
        Route::post('/facts/position/{id}/update', [App\Http\Controllers\Admin\FactController::class, 'updatePosition'])->name('facts.position.update');

        Route::resource('/why-wes', App\Http\Controllers\Admin\WhyWeController::class);
        Route::post('/why-wes/position/{id}/update', [App\Http\Controllers\Admin\WhyWeController::class, 'updatePosition'])->name('why-wes.position.update');

        Route::resource('/abouts', App\Http\Controllers\Admin\AboutController::class);
        Route::post('/abouts/position/{id}/update', [App\Http\Controllers\Admin\AboutController::class, 'updatePosition'])->name('abouts.position.update');

        Route::resource('/services', App\Http\Controllers\Admin\ServiceController::class);
        Route::post('/services/position/{id}/update', [App\Http\Controllers\Admin\ServiceController::class, 'updatePosition'])->name('services.position.update');

        Route::resource('/tag-description-services', App\Http\Controllers\Admin\TagDescriptionServiceController::class);
        Route::post('/tag-description-services/position/{id}/update', [App\Http\Controllers\Admin\TagDescriptionServiceController::class, 'updatePosition'])->name('tag-description-services.position.update');

        Route::resource('/description-services', App\Http\Controllers\Admin\DescriptionServiceController::class);
        Route::post('/description-services/position/{id}/update', [App\Http\Controllers\Admin\DescriptionServiceController::class, 'updatePosition'])->name('description-services.position.update');

        Route::resource('/tags', App\Http\Controllers\Admin\TagController::class);
        Route::post('/tags/position/{id}/update', [App\Http\Controllers\Admin\TagController::class, 'updatePosition'])->name('tags.position.update');

        Route::resource('/blogs', App\Http\Controllers\Admin\BlogController::class);
        Route::post('/blogs/position/{id}/update', [App\Http\Controllers\Admin\BlogController::class, 'updatePosition'])->name('blogs.position.update');

        Route::resource('blogs.reviews', App\Http\Controllers\Admin\ReviewController::class);
        Route::post('/reviews/position/{id}/update', [App\Http\Controllers\Admin\ReviewController::class, 'updatePosition'])->name('reviews.position.update');

        Route::resource('/tag-masters', App\Http\Controllers\Admin\TagMasterController::class);
        Route::post('/tag-masters/position/{id}/update', [App\Http\Controllers\Admin\TagMasterController::class, 'updatePosition'])->name('tag-masters.position.update');

        Route::resource('/masters', App\Http\Controllers\Admin\MasterController::class);
        Route::post('/masters/position/{id}/update', [App\Http\Controllers\Admin\MasterController::class, 'updatePosition'])->name('masters.position.update');

        Route::resource('/phones', App\Http\Controllers\Admin\PhoneController::class);
        Route::resource('/emails', App\Http\Controllers\Admin\EmailController::class);

        Route::resource('/subscribes', App\Http\Controllers\Admin\SubscribeController::class);
        Route::resource('/feedbacks', App\Http\Controllers\Admin\FeedbackController::class);
    });
});

Route::get('optimize-clear', function () {
    Artisan::call('optimize:clear');
    return back()->with('fail', 'Optimize clear!');
})->name('optimizeClear');

Route::get('storage-link', function () {
    Artisan::call('storage:link');
    return back()->with('fail', 'Storage link!');
})->name('storageLink');

backend/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

backend/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;

use App\Http\Requests\Admin\User\StoreUserRequest;
use App\Http\Requests\Admin\User\UpdateUserRequest;

use App\Http\Requests\Admin\User\UpdateUserStatusRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\DB;
use App\Services\Admin\User\UserService;

class UserController extends Controller
{
    public function __construct(protected UserService $userService)
    {
        $this->middleware('auth:admin');
        $this->middleware('permission:все-пользователи', ['only' => ['index','show']]);
        $this->middleware('permission:создание-пользователя', ['only' => ['create','store']]);
        $this->middleware('permission:редактирование-пользователя', ['only' => ['edit','update', 'updateUserStatus']]);
        $this->middleware('permission:удаление-пользователя', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        $users = $this->userService->getUsers();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreUserRequest $request): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $adminEmail = config('mail.from.address');
            $m = ' Логин и Пароль отправлен на эту почту ' . $adminEmail;
            $this->userService->createUser($data, $adminEmail);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.users.index')->with('success', config('sessionmessages.successfully_added') . $m);
    }

    /**
     * Display the specified resource.
     */
    public function show(User $user): View
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(User $user): View
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateUserRequest $request, User $user): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $adminEmail = config('mail.from.address');
            $m = $this->userService->updateUser($user, $data, $adminEmail);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.users.index')->with('success', config('sessionmessages.successfully_updated') . $m);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(User $user): RedirectResponse
    {
        DB::beginTransaction();
        try {
            $this->userService->deleteUser($user);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.users.index')->with('success', config('sessionmessages.successfully_deleted'));
    }

    public function updateUserStatus(UpdateUserStatusRequest $request, string $id): RedirectResponse
    {
        $data = $request->validated();

        DB::beginTransaction();
        try {
            $this->userService->updateUserStatus($id, $data);

            DB::commit();
        } catch (\Exception $exception) {
            DB::rollBack();

            return back()->withInput()->withErrors($exception->getMessage());
        }

        return redirect()->route('admin.users.index')->with('success', config('sessionmessages.successfully_updated'));
    }
}

backend/resources/views/admin/users/_form.blade.php
<x-forms.simple-text :model="$user ?? null" name="name" label="Имя" />

<x-forms.simple-text :model="$user ?? null" name="email" label="Email" />

<div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
    <label for="password" class="control-label">@if($formMode == 'create') {{ 'Пароль' }} @else {{ 'Обновить Пароль' }} @endif</label>
    <input class="form-control" name="password" type="text" id="password">
    {!! $errors->first('password', '<p class="text-danger">:message</p>') !!}
</div>
<hr>

@if($formMode == 'create')
    <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : ''}}">
        <label for="password_confirmation" class="control-label">{{ 'Повторить Пароль' }}</label>
        <input class="form-control" name="password_confirmation" type="text" id="password_confirmation">
        {!! $errors->first('password_confirmation', '<p class="text-danger">:message</p>') !!}
    </div>
    <hr>
@endif

@if($formMode == 'edit')
    <input name="user_id" type="hidden" value="{{$user->id}}">
@endif

<x-forms.simple-button :formMode="$formMode" />

backend/resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Добавить Пользователя')

@section('content_header')
    <h1>Добавить Пользователя</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.users.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.users.store') }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            @include ('admin.users._form', ['formMode' => 'create'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Редактировать Пользователя')

@section('content_header')
    <h1>Редактировать Пользователя</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.users.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                        </div>
                    </div>
                    <div class="card-body">

                        <form method="POST" action="{{ route('admin.users.update', ['user' => $user]) }}" accept-charset="UTF-8" class="form-horizontal" enctype="multipart/form-data">
                            {{ method_field('PATCH') }}
                            {{ csrf_field() }}

                            @include ('admin.users._form', ['formMode' => 'edit'])

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Пользователи')

@section('content_header')
    <h1>Пользователи</h1>
@stop

@section('content')

    @include('components.alert')

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            @can('создание-пользователя')
                                <a href="{{ route('admin.users.create') }}" class="btn btn-success btn-sm" title="Добавить">
                                    <i class="fa fa-plus" aria-hidden="true"></i> Добавить
                                </a>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive" id="tblSort">
                            <table id="tblData" class="table table-bordered table-striped dataTable dtr-inline">
                                <thead>
                                    <tr>
                                        <form>
                                            <th colspan="3">
                                                <div class="input-group input-group-sm">
                                                    <input type="text" name="search[name]" class="form-control float-right" placeholder="Название" value="{{request()->get('search')['name'] ?? ''}}">
                                                </div>
                                            </th>
                                            <th colspan="2">
                                                <div class="input-group input-group-sm">
                                                    <select name="search[status]" class="form-control float-right">
                                                        <option value="1" {{ (isset(request()->get('search')['status']) && request()->get('search')['status'] == 1) ? 'selected' : '' }}>Активирован</option>
                                                        <option value="0" {{ (isset(request()->get('search')['status']) && request()->get('search')['status'] == 0) ? 'selected' : '' }}>Деактивирован</option>
                                                    </select>
                                                    <div class="input-group-append">
                                                        <button type="submit" class="btn btn-default">
                                                            <i class="fas fa-search"></i>
                                                        </button>
                                                    </div>
                                                </div>
                                            </th>
                                            <th>
                                                <a href="{{ route('admin.users.index') }}" title="Сбросить поиск" class="btn btn-success btn-sm">
                                                    <i class="fa fa-spinner" aria-hidden="true"></i> Сбросить поиск
                                                </a>
                                            </th>
                                        </form>
                                    </tr>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>Имя</th>
                                        <th>Email</th>
                                        <th>Статус</th>
                                        <th>Действие</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $count = 1;
                                    @endphp
                                    @forelse($users as $item)
                                        <tr>
                                            <td>
                                                {{$users->perPage()*($users->currentPage()-1)+$count}}
                                            </td>
                                            <td data-id="{{$item->id}}">
                                                {{ $item->id }}
                                            </td>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>
                                                @if($item->status == 1)
                                                    <span class="badge rounded-pill bg-success">Активирован</span>
                                                @else
                                                    <span class="badge rounded-pill bg-danger">Деактивирован</span>
                                                @endif
                                            </td>
                                            <td>
                                                @can('все-пользователи')
                                                    <form method="POST" action="{{ route('admin.users.update.status', $item->id) }}" accept-charset="UTF-8" style="display:inline;">
                                                        {{ method_field('PATCH') }}
                                                        {{ csrf_field() }}
                                                        <input type="hidden" name="status" value="{{ $item->status == 1 ? 0 : 1 }}">
                                                        <button type="submit" class="btn btn-{{ $item->status == 1 ? 'danger' : 'success' }} btn-sm mb-2" title="@if($item->status == 1) Деактивировать @else Активировать @endif">
                                                            @if($item->status == 1)
                                                                <i class="fa fa-lock" aria-hidden="true"></i>
                                                            @else
                                                                <i class="fa fa-lock-open" aria-hidden="true"></i>
                                                            @endif
                                                        </button>
                                                    </form>

                                                    <a href="{{ route('admin.users.show', ['user' => $item]) }}" class="btn btn-info btn-sm mb-2" title="Просмотр">
                                                        <i class="fa fa-eye" aria-hidden="true"></i>
                                                    </a>
                                                @endcan
                                                @can('редактирование-пользователя')
                                                    <a href="{{ route('admin.users.edit', ['user' => $item]) }}" class="btn btn-primary btn-sm mb-2" title="Редактировать">
                                                        <i class="fa fa-fw fa-edit" aria-hidden="true"></i>
                                                    </a>
                                                @endcan
                                                @can('удаление-пользователя')
                                                    <form method="POST" action="{{ route('admin.users.destroy', ['user' => $item]) }}" accept-charset="UTF-8" style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-danger btn-sm mb-2" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $item->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $item->name }}?&quot;)">
                                                            <i class="fa fa-trash" aria-hidden="true"></i>
                                                        </button>
                                                    </form>
                                                @endcan
                                            </td>
                                        </tr>
                                        @php
                                            $count++;
                                        @endphp
                                    @empty
                                        <tr>
                                            <td align="center" class="text-danger" colspan="6">
                                                Пользователи не найдены
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th>#</th>
                                        <th>ID</th>
                                        <th>Имя</th>
                                        <th>Email</th>
                                        <th>Статус</th>
                                        <th>Действие</th>
                                    </tr>
                                </tfoot>
                            </table>
                            <div class="pagination-wrapper">
                                @if(is_object($users))
                                    {!! $users->links() !!}
                                @endif
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('css')

@stop

@section('js')

@stop

backend/resources/views/admin/users/show.blade.php
@extends('adminlte::page')

@section('title', 'Просмотр Пользователя')

@section('content_header')
    <h1>Просмотр Пользователя</h1>
@stop

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <div class="card-title">
                            <a href="{{ route('admin.users.index') }}" class="btn btn-warning" title="Назад">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i> Назад
                            </a>
                            @can('редактирование-пользователя')
                                <a href="{{ route('admin.users.edit', ['user' => $user]) }}" class="btn btn-primary" title="Редактировать">
                                    <i class="fa fa-fw fa-edit" aria-hidden="true"></i> Редактировать
                                </a>
                            @endcan
                            @can('удаление-пользователя')
                                <form method="POST" action="{{ route('admin.users.destroy', ['user' => $user]) }}" accept-charset="UTF-8" style="display:inline">
                                    {{ method_field('DELETE') }}
                                    {{ csrf_field() }}
                                    <button type="submit" class="btn btn-danger" title="Удалить" onclick="return confirm(&quot;Подтвердите удаление {{ $user->name }}!&quot;) && confirm(&quot;Вы уверены что хотите удалить {{ $user->name }}?&quot;)">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Удалить
                                    </button>
                                </form>
                            @endcan
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <th>ID</th>
                                        <td>{{ $user->id }}</td>
                                    </tr>
                                    <tr>
                                        <th> Имя </th>
                                        <td> {{ $user->name }} </td>
                                    </tr>
                                    <tr>
                                        <th> Email </th>
                                        <td> {{ $user->email }} </td>
                                    </tr>
                                    <tr>
                                        <th> Дата Создание </th>
                                        <td> {{ $user->created_at?->format('d.m.Y') }} </td>
                                    </tr>
                                    <tr>
                                        <th> Дата Обновление </th>
                                        <td> {{ $user->updated_at?->format('d.m.Y') }} </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection